import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TeamListContextProvider from "./context/TeamListContextProvider";
import QuestionContextProvider from "./context/QuestionContextProvider";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "guniguni nyo lang yon",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" data-theme="cupcake">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
            <TeamListContextProvider>
               <QuestionContextProvider>{children}</QuestionContextProvider>
            </TeamListContextProvider>
         </body>
      </html>
   );
}
